// node --test (Node strips the types): no test framework needed.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { labelAt, parseSym, resolve, withLabels } from './sym.ts';

// Shaped like `rgblink -n game.sym` output, written by hand.
const SYM = `; File generated by rgblink
00:0150 Main
00:0156 Main.loop
00:2F1A UpdateSprites
01:4123 BankOneThing
02:4123 BankTwoThing
00:C000 wShadowOAM
this line is not a symbol

00:FF80 hDMA ; trailing comment
`;
const t = parseSym(SYM);

test('parses every symbol, skips comments and counts a malformed line', () => {
  assert.equal(t.byName.size, 7);
  assert.deepEqual(t.byName.get('Main.loop'), { bank: 0, addr: 0x0156, name: 'Main.loop' });
  assert.deepEqual(t.byName.get('hDMA'), { bank: 0, addr: 0xff80, name: 'hDMA' });
  assert.equal(t.skipped, 1);
});

test('a switchable-bank address takes the label of the bank mapped now', () => {
  assert.equal(labelAt(t, 0x4123, 2), 'BankTwoThing');
  assert.equal(labelAt(t, 0x4123, 1), 'BankOneThing');
  assert.equal(labelAt(t, 0x4123, 3), undefined);
  assert.equal(labelAt(t, 0x0150, 5), 'Main');
  assert.equal(labelAt(t, 0xc000, 5), 'wShadowOAM');
});

test('operands become labels, unlisted addresses stay hex', () => {
  assert.equal(withLabels(t, 'CALL $2F1A', 1), 'CALL UpdateSprites');
  assert.equal(withLabels(t, 'JR NZ, $0156', 1), 'JR NZ, Main.loop');
  assert.equal(withLabels(t, 'LD [$C000], A', 1), 'LD [wShadowOAM], A');
  assert.equal(withLabels(t, 'CALL $1234', 1), 'CALL $1234');
  assert.equal(withLabels(t, 'LD A, $01', 1), 'LD A, $01');
});

test('resolves names and hex addresses', () => {
  assert.equal(resolve(t, 'Main.loop'), 0x0156);
  assert.equal(resolve(t, '$0150'), 0x0150);
  assert.equal(resolve(t, '0150'), 0x0150);
  assert.equal(resolve(t, 'Nope'), undefined);
  assert.equal(resolve(parseSym(''), 'ff80'), 0xff80);
});
